CREATE TABLE IF NOT EXISTS transaction
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_document     VARCHAR(255)                            NOT NULL,
    credit_card_token VARCHAR(255)                            NOT NULL,
    "value"           DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);