name: Tests check

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17
      - run: mvn -T 5 clean -B test
